apiVersion: v1
kind: Service
metadata:
  labels:
    app: student-rest
    env: dev
  name: student-rest
spec:
  ports:
    - port: 8080
      name: "student-rest"
  selector:
    app: student-rest

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: student-rest
  labels:
    app: student-rest
    env: dev
spec:
  selector:
    matchLabels:
      app: student-rest
      env: dev
  replicas: 2
  template:
    metadata:
      labels:
        app: student-rest
        env: dev
    spec:
      containers:
        - name: student-rest
          image: preetamdutta/student-rest:latest
          imagePullPolicy: IfNotPresent